// FAKE DATA
export const desserts = [
  {
    id: 1,
    title: "Chocolate Cake",
    url: "https://m.media-amazon.com/images/I/81eFq-feqQL._SL1500_.jpg",
    originalPrice: 35.95,
    salePrice: 14.95,
    rating: 4.5,
  },
  {
    id: 2,
    title: "Vanilla Cake",
    url: "https://thescranline.com/wp-content/uploads/2025/02/VANILLA-CAKE-25-S-01.jpg",
    originalPrice: 35,
    salePrice: null,
    rating: 5,
  },
  {
    id: 3,
    title: "Strawberry Cake",
    url: "https://www.eat2gather.net/wp-content/uploads/2013/07/strawberry-cake-hero-1-2-500x500.jpg",
    originalPrice: 29,
    salePrice: null,
    rating: 5,
  },
  {
    id: 4,
    title: "Lemon Cake",
    url: "https://www.modernhoney.com/wp-content/uploads/2024/02/Best-Lemon-Cake-4-crop-scaled.jpg",
    originalPrice: 35,
    salePrice: 19,
    rating: 4.5,
  },
  {
    id: 5,
    title: "7 up Cake",
    url: "https://www.theseasonedmom.com/wp-content/uploads/2024/10/7-up-cake-pound-cake-7-500x500.jpg",
    originalPrice: 32,
    salePrice: null,
    rating: 5,
  },
  {
    id: 6,
    title: "Bread Pudding",
    url: "https://simplyhomecooked.com/wp-content/uploads/2021/11/bread-pudding-recipe-6.jpg",
    originalPrice: 30,
    salePrice: 12.5,
    rating: 5,
  },
  {
    id: 7,
    title: "Vegan Chocolate Cupcakes",
    url: "https://addictedtodates.com/wp-content/uploads/2022/08/vegan-chocolate-cupcakes.jpg",
    originalPrice: 20,
    salePrice: 10,
    rating: 4,
  },
  {
    id: 8,
    title: "Vegan Vanilla Cupcakes",
    url: "https://earthly-provisions.com/wp-content/uploads/2024/04/Vegan-Vanilla-Cupcakes-9.jpg",
    originalPrice: 20,
    salePrice: 9.95,
    rating: 4.5,
  },
  {
    id: 9,
    title: "Vegan Red Velvet Cupcakes",
    url: "https://www.danceswithknives.com/wp-content/uploads/2026/02/vegan-red-velvet-cupcakes-square-group.jpg",
    originalPrice: 20,
    salePrice: 9.95,
    rating: 4.5,
  },
  {
    id: 10,
    title: "Chocolate Chip Cookies",
    url: "https://www.modernhoney.com/wp-content/uploads/2021/03/Chocolate-Chip-Coconut-Cookies-4-crop-scaled.jpg",
    originalPrice: 25,
    salePrice: null,
    rating: 5,
  },
  {
    id: 11,
    title: "Oreo Cupcake",
    url: "https://sugarandsparrow.s3.us-west-2.amazonaws.com/flour/wp-content/uploads/2025/08/13095607/Oreo-Cupcakes-Recipe-header.jpeg",
    originalPrice: 20,
    salePrice: 10,
    rating: 5,
  },
  {
    id: 12,
    title: "Honey Cupcake",
    url: "https://wholesomepatisserie.com/wp-content/uploads/2024/08/honey-cupcakes-recipe.jpg",
    originalPrice: 25,
    salePrice: 12.95,
    rating: 4.5,
  },
];